name: baraka_flutter_native_contact_picker
description: "A Flutter plugin for picking a contact from the address book."
version: 0.0.10
homepage: https://github.com/barakatech/flutter_native_contact_picker

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.baraka.flutter_native_contact_picker
        pluginClass: FlutterNativeContactPickerPlugin
      ios:
        pluginClass: FlutterNativeContactPickerPlugin